### ISSUE TITLE
Support ZIO's effect types and runtime system

### ISSUE THREAD

**Issue by andreamarcolin** [bkirwi/decline#101]
As a user, I would expect to be able to use ZIO's runtime system, and use its effect types, like Task.
I think these could be done with two improvements:

- Separating CommandIOApp abstract class definition (with its abstract main method) from the wiring to the cats-effect runtime system (IOApp), and letting the abstract method be polymorphic in the effect type.
- Add two implementations of this abstract class: one which is identical to how it looks now, for the cats-effect runtime system, and one for the ZIO runtime system (maybe in another module, or just depending on ZIO in the effect module?)

With this approach, even Monix could be supported by creating a third implementation based on his own runtime system (TaskApp). Some insights on why each IO monad implementation benefits from his own runtime system can be found [here](https://typelevel.org/cats-effect/datatypes/ioapp.html#why-is-it-specialized-for-io).

Let me know what you think about this and if you are interested in supporting ZIO at all, if yes I could try to sketch a PR.

**Comment by bkirwi** [comment]
I'm generally cool with doing things that make life easier for ZIO users, but I'm not sure we want to get in the business of doing a `*App` for every framework. (The page you linked also mentions how `CommandIOApp` can be used with any `F[_]: Effect`.)

One thing that could be useful is a `def run[F[_], A](command: Command[A], args: List[String]): F[A]` which did the arg juggling and the help printing... that seems like it should expose the most tedious logic, and make using zio and decline together a one-liner. Thoughts?

**Comment by andreamarcolin** [comment]
I see your point.
Starting with the polymorphic `run` as you suggested could be enough to enable most of the ZIO/Monix users, so I am fine with it. 

Should I go on and implement it as a PR?

**Comment by bkirwi** [comment]
Sure, sounds great!

**Comment by andreamarcolin** [comment]
Sorry for the long delay, I was pretty busy last month. Just submitted a PR 😄
