### ISSUE TITLE
Interactive mode?

### ISSUE THREAD

**Issue by kubukoz** [bkirwi/decline#125]
It would be nice if we could run the application once and then have a sort of REPL in which we could write a command, wait for its completion and write another one. As a further step (much further down the line) commands could change states, resulting in the available command set changing.

The major upside of having this is of course fast startup (not loading a fresh JVM on every time & not allocating resources, if the app has any) and not having to write the application's path every time.

**Comment by kubukoz** [comment]
I'm willing to give it a try if it sounds like a good idea :)

**Comment by bkirwi** [comment]
it's an interesting idea!

i'm not sure it's a great fit for the core library, though, for a couple
reasons:
- decline tries to stick to well-established precedent for the interfaces
it generates... new features are usually motivated by things like the posix
standard or common usage in the wild. i'm not aware of any common software
out there that uses this style...  but would be happy to be proven wrong!
- it shouldn't be too hard for users to implement without changes to
decline... eg [tuco](
https://tpolecat.github.io/tuco/docs/todo-list.html) implements something
kind of similar already.

does that make sense?

**Comment by bkirwi** [comment]
closing to keep things tidy, but feel free to follow up!
