### ISSUE TITLE
can we publish for cats 1.0.0-MF

### ISSUE THREAD

**Issue by johnynek** [bkirwi/decline#15]
I am in a minor dependency hell where I need cats 1.0.0 for something, but decline won't run with cats 1.0.0

I see a 0.4.0-M1 tagged, but I don't see it in maven central. Is there a way I can get it?

**Comment by bkirwi** [comment]
Just cut a `0.4.0-M2` release -- been meaning to do one for the `refined` stuff anyways. (M1 was the last release before I got Sonatype sorted.) Can you see if that works for you?

OOC -- any idea when `cats` is expected to hit 1.0?

**Comment by johnynek** [comment]
@bkirwi very soon. There is a push to get all the final things done (I would guess 1 month maybe)

**Comment by johnynek** [comment]
and thank you so much! This unblocked me!
