### ISSUE TITLE
How to conditionally require an option given the value of another?

### ISSUE THREAD

**Issue by JLofgren** [bkirwi/decline#165]
This is mostly a question, and possibly a request to add more examples to documentation.

Suppose I have:

```
val vehicleType: Opts[VehicleType] = ???
```

If the user specifies vehicleType `Car`, then I want to require another option:

```
val licensePlate: Opts[String] = ???
```

If the user specifies vehicleType `Bicycle`, then I don't want to require any other options.

How can I accomplish this?

**Comment by bkirwi** [comment]
The short answer is, basically, two ways:

One is to not encode this at a structural level, and use validation to
eliminate the combinations that don't make sense.

The other is to use flags for the vehicle type, which changes the usage to
something like `--car --license-plate XXXXXX`. I prefer this approach: it
produces better help messages and captures the structure you have better.

Happy to elaborate on either option if it's unclear what I'm talking about!

**Comment by JLofgren** [comment]
The second approach would make sense for me, too. So, how do I require --license-plate if --car is set?

**Comment by bkirwi** [comment]
```scala
case class Car(licensePlate: String)

val carFlag: Opts[Unit] = Opts.flag("car", "...")
val licensePlate: Opts[String] = ???
(carFlag, licensePlate).mapN { (_, license) => Car(license) }
```

Basically it works like [the example](http://ben.kirw.in/decline/usage.html#combining-options) in the guide... but the "trick" is to add the extra flag at the start.

For multiple vehicle types, you probably want `Car` to extend some `sealed trait VehicleType`, define an `Opts` instance like the above for each of them, and then `orElse` them all together.

**Comment by bkirwi** [comment]
Assuming this is answered, but feel free to reopen if that doesn't cover it!
