### ISSUE TITLE
Clarify Get Started

### ISSUE THREAD

**Issue by pme123** [bkirwi/decline#167]
I just wanted to give Decline a shot. But going through the Get Started gave me:

```
[109/109] cli.run 
Hello world!
nbszmbp013:camundala mpa$ hello-world --help
bash: hello-world: command not found
```
I clearly miss a step. But there is no clue in the Get Started of the Documentation.

What do I miss here?

**Comment by bkirwi** [comment]
it sounds like cli.run is how you have your program set up to run, so
asking for help would just be `cli.run --help`.

(decline doesn't do anything special to build orr create aliases etc for
you... it's just a command line parser, and people build scala all sorts of
different ways of course!)

Le ven. 1 mai 2020 à 00:50, Pascal Mengelt <notifications@github.com> a
écrit :

**Comment by pme123** [comment]
Ah thanks - I just started  with decline - so I had the concept of an interactive console. 

So I thought you run the program - and then interact with it over the terminal.

**Comment by sinanspd** [comment]
I would like to revisit this issue and suggest that the documentation at least clarifies how it is set up to run. Similarly I can do 

`sbt "run  --help"`

But it is unclear to me how the example got to

`hello-world --help`

what sbt command registers the program as a launcher?

**Comment by bkirwi** [comment]
I think ultimately the answer is "however you would normally do that" - decline's not tied to any particular build tool or process for creating executables, and there's enough diversity there in terms of how people actually do it that

**Comment by sinanspd** [comment]
Yes. That would be perfect. A new adapter can not be expected to have understanding of `CommandApp`.  Having `name = "hello-word` immediately followed by `hello-world --help` create confusion that  `CommandApp` might be creating an executable behind the scenes, similar to how `sbt-pack`  does (tho i guess it wouldn't be possible without a compiler plug-in). Do you mind one of us doing a PR , or do you want to write something yourself?

**Comment by bkirwi** [comment]
Going through old issues this week, and I realized I never followed up on this. Apologies!

Just updated the documentation to clarify this case.
