### ISSUE TITLE
Milestone for cats 1.0.0-RC1?

### ISSUE THREAD

**Issue by tpolecat** [bkirwi/decline#17]
I see that a PR was merged for 1.0.0-RC1 … is there a milestone build out there?

**Comment by bkirwi** [comment]
Not yet! I think I neat to make one more tweak before I can release -- move a dep back into test scope -- but should be set otherwise.

In the meantime, I think the last milestone release should be forward-compatible?

**Comment by bkirwi** [comment]
Aight, should be up as `0.4.0-RC1`! Let me know if that works?

**Comment by tpolecat** [comment]
Waiting on another upstream dependency before I can try this but I'll let you know. Thanks!

**Comment by tpolecat** [comment]
👍 works! Thank you.
