### ISSUE TITLE
Argument.fromMap

### ISSUE THREAD

**Issue by johnynek** [bkirwi/decline#187]
@bkirwi what do you think of a method like this:

```scala
  def fromMap[A](defmeta: String, nameToValue: Map[String, A]): Argument[A] =
         new Argument[A] {
           def defaultMetavar: String = defmeta
           val keys = nameTo.keys.toList.sorted.mkString(", ")
           def read(string: String): ValidatedNel[String, A] =
             nameToValue.get(string) match {
               case Some(t) => Validated.valid(t)
               case None =>  
                 Validated.invalidNel(s"unknown value: $string, expected one of: $keys")
             }

```

This can make it convenient to provide a string to value mapping and get an Argument from it. This is useful for custom enum-like ADTs.

**Comment by bkirwi** [comment]
Seems fine to me!

(I'm never sure where to draw the line on these sorts of helpers... there's value in keeping the API surface small, but they can be convenient!)

You'd want to special-case the 0 and 1-element map case in the error message for readability, but that's an easy change.

**Comment by johnynek** [comment]
It's an art for sure, but I think if we can make the common uses easy and not add dependencies, I am generally open to changes that reduce work for users. The art is seeing which change is likely to help a number of users and be easily understood.

**Comment by johnynek** [comment]
Okay, I took your suggestions for special messages for 0 and 1 and made this PR: #193
