### ISSUE TITLE
update to scalajs 1.0

### ISSUE THREAD

**Issue by johnynek** [bkirwi/decline#189]
I can't update a project of mine to scalajs 1.0 due to being blocked by decline.

any objections?

**Comment by bkirwi** [comment]
No objection! The automatic PR seems to have broken something, though: https://github.com/bkirwi/decline/pull/180

Haven't investigated deeply yet!

**Comment by johnynek** [comment]
see #192 

That explains the issues. A few deps needed to be bumped.
