### ISSUE TITLE
Missing decline-refined in Maven Central

### ISSUE THREAD

**Issue by alonsodomin** [bkirwi/decline#19]
It seems that the `decline-refined` module has not been published in Maven Central yet. Would it be possible to publish it for Scala 2.11 and 2.12?

**Comment by bkirwi** [comment]
Ugh, right you are -- this looks like a bug in my release process. Thanks for flagging this! I'll try and get this sorted out tomorrow...

**Comment by bkirwi** [comment]
Hey -- just pushed `decline-refined` to maven central for the last release: `0.4.0-RC1`. (Which is based on the 1.0 release candidate of `cats`.) I'm also replacing my slightly baroque bintray-to-sonatype publish cycle with sonatype-only, so this shouldn't happen again.
