### ISSUE TITLE
Combining Opts.flag with Opts.env using orElse

### ISSUE THREAD

**Issue by digitaltopo** [bkirwi/decline#191]
Is it possible to combine a flag with fallback to environment variable and ultimately a default value?

ex)

```scala
...
val myArg = (Opts
    .flag(
      "with-foo",
      help = "With foo"
    ) orElse Opts
    .env[String]("WITH_FOO", help = "With foo", metavar = "true||false")) orFalse
...
```
The desired outcome is to allow for CLI to use the `--with-foo` flag but alternatively allow users to instead specify `WITH_FOO=true` as an env variable, with both cases defaulting to `false`.

Because of the [intentional missing instances](http://ben.kirw.in/decline/arguments.html#missing-instances) we can't set `Opts.env[Boolean]`, but in the example above the `orElse` gives a warning that `a type was inferred to be Any; this may indicate a programming error.` and `orFalse` gives an error `Cannot prove that Any <:< Unit.`

Any guidance on how best to achieve the desired outcome?

I have also tried to validate and then cast the `Opts.env` value, then use `withDefault("false")` instead of `orFalse` for the default fallback value:

```scala
...
  Opts
    .env[String]("WITH_FOO", help = "With foo", metavar = "true||false")
    .validate("Value must be Boolean") { (s: String) => Try(s.toBoolean).getOrElse(false) }
    .map { _.toBoolean } withDefault ("false")
...
```

**Comment by bkirwi** [comment]
Sure! And keep in mind that orFalse is just defined as
.as(true).withDefault(false).

In order, you prefer the flag, then the env var, then the default value. So
you want something like:

val flag = Opts.flag(...).as(true)
val env = Opts.env(...).mapValidated(...)
val all = flag.orElse(env).withDefault(false)

Both your examples show a little bit of type confusion... in the first you
combine an Opts of Unit to one of String, and in the other you use String
as a default value for an Opts of Boolean. Notice that in the code above
all the vals have type Boolean, so we can combine them without issue.

**Comment by digitaltopo** [comment]
Thanks for the help, here's what I ended up with if anyone else has the same question:

```scala
Opts
    .flag(
      "with-foo",
      help = "With foo"
    )
    .orFalse orElse Opts
    .env[String]("WITH_FOO", help = "With foo", metavar = "true||false")
    .mapValidated { s =>
      if (Try(s.toBoolean).getOrElse(false)) Validated.valid(s.toBoolean)
      else Validated.invalidNel("Value must be Boolean")
    } withDefault (false)
```
