### ISSUE TITLE
Add --arg=value format

### ISSUE THREAD

**Issue by chuwy** [bkirwi/decline#195]
We have [a project](https://github.com/snowplow/enrich/issues/266) on top of [scio](https://github.com/spotify/scio/) which is being on top of Apache Beam / Google Dataflow supports only `--arg=value` format as opposed to decline's `--arg value`. Scio provides its own tooling for argparsing, but I find decline style way more composable, type-safe and just purely awesome.

I was wondering if somebody considered adding an option for equals sign or would it be considered as contribution at all.

**Comment by bkirwi** [comment]
Hey, thank you!

The --arg=value syntax is actually already supported... though I see we
don't actually call that out in the docs. (Oops!) So hopefully thanks not a
blocker for your project, though do follow up if you run into issues with
it.
