### ISSUE TITLE
Idea: Opts.repeated

### ISSUE THREAD

**Issue by daddykotex** [bkirwi/decline#251]
Thanks for your library. Recently I've used it and I wondered if it would make sense to have an operator to turn an `Opts[String]` into an `Opts[NEL[String]]`.

Suppose you have an option defined like that:

```scala
val group: Opts[String] =
    Opts
      .option[String](
        long = "group",
        help = "Group that exists."
      )
```

If one subcommand takes the `group` like, `command1 --group group` but another command takes it repeatedly, like: `command2 --group group1 --group group2`, you can't reuse your definition.

Would a `group.repeated` make sense? Or perhaps a `Opts.repeat(group)`?

Anyhow, let me know, I can handle the implementation, I just don't want to waste your time.

**Comment by bkirwi** [comment]
This was one of the tricky design problems I remember from the early days of `decline`... even considered not having the "plural" methods at all, and using a combinator like you suggest for all repeated options.

> Would a group.repeated make sense?

I think it does make sense for the case you describe! But it's hard to come up with a reasonable behaviour for `subcommand.repeated`, `group.repeated.repeated`, or `(group, group).tupled.repeated` and things like that. Which makes it a bit dicey to support as a general method on `Opts`.

You could maybe come up with an `Opts` subtype that supports repeating, and give `Opts.option` that more specific type... but introducing a new type introduces new complexity for all users, and I'd be pretty hesitant.

**Comment by daddykotex** [comment]
Yeah, I totally agree, and when I looked up the source code to see how I would implement it, I struggle to figure that out.

But to be honest, I found that confusing, when getting started, that both `Opts.option(...)` has the same type as `Opts.subcommand(...)`. In practice it turns out to be fine, because they compose nicely, but I could not understand it in the beginning.

**Comment by daddykotex** [comment]
If you ever decides that it can be done, I'm happy to help, in the meantime, I'll close the issue
