### ISSUE TITLE
Migration to Cats Effect 3

### ISSUE THREAD

**Issue by catostrophe** [bkirwi/decline#254]
This is to track the efforts to migrate to CE3.

WIP: #206

See: typelevel/cats-effect#1330

**Comment by kubukoz** [comment]
I believe this can be closed.

**Comment by TonioGela** [comment]
Is it me or I still cannot see a release that contains at least CE 3.0.0? The [last one I can see at the moment](https://search.maven.org/classic/#search%7Cgav%7C1%7Cg%3A%22com.monovore%22%20AND%20a%3A%22decline-effect_2.13%22) it's 2.0.0-RC1 that seems to depend on [CE 3.0.0-RC2](https://github.com/bkirwi/decline/blob/v2.0.0-RC1/build.sbt#L72)

At the moment using sbt 1.5.0-RC1 and `versionScheme` the output I get is this
```
[error] 	* org.typelevel:cats-effect_2.13:3.0.1 (early-semver) is selected over 3.0.0-RC2
[error] 	    +- dev.toniogela:effectiveorganizer_2.13:0.1.0-SNAPSHOT (depends on 3.0.1)
[error] 	    +- com.monovore:decline-effect_2.13:2.0.0-RC1         (depends on 3.0.0-RC2)
```
That release is ~15 days old while the PRs for CE 3.0.0 and 3.0.1 are just a couple of days old.

**Comment by catostrophe** [comment]
It's not released yet

**Comment by bkirwi** [comment]
Had some issues with Sonatype, but this should be fully out and available now!
