### ISSUE TITLE
proposal: remove defaultMetaVar from Argument

### ISSUE THREAD

**Issue by johnynek** [bkirwi/decline#27]
If we did this, we could imagine that Argument can be a coherent typeclass. As it is, it couples information from parsing and the semantics of how a particular argument is being used.

Instead, we could require the metavar at the Opts site, and if we did that, we could really give a batteries totally included suite of Argument instances for all common types. Indeed, we could put them in the Argument companion for primitives and standard types (BigInt, Path, uuid, etc...)

**Comment by bkirwi** [comment]
> Instead, we could require the metavar at the Opts site, and if we did that, we could really give a batteries totally included suite of Argument instances for all common types.

FWIW, I don't think the metavar situation is an obstacle to this. For the current `Argument` implementations, the metavar is just a brief description of the type... and there's no obstacle to having `--whatever-id <uuid>` or similar. I think including the batteries here makes sense whether / not `metavar` gets removed from the typeclass.

On the other hand, getting rid of the default would be worth it if it led to better CLIs!

The metavar shows up in a couple places currently. For options, you get things like `Usage: cmd --source <path> --dest <path>`. For positional arguments, you get `Usage: cmd <path> <path>`. The second form is pretty awkward, and I think I'm sympathetic to dropping the default metavar there.

OTOH, I sort of like the first form... using the "type" as the metavar there is pretty common and reads well. If folks are going to use the type name _anyways_, plumbing it through automatically is handy and makes it harder for types and documentation to fall out of sync. (And it gets even better when people use richer types!) I'd be much more hesitant to make that change.

**Comment by non** [comment]
Here's a possible implementation: https://github.com/bkirwi/decline/pull/28

**Comment by bkirwi** [comment]
(See the linked PR for the resolution on this!)
