### ISSUE TITLE
Arguments from environment variables

### ISSUE THREAD

**Issue by alexjg** [bkirwi/decline#32]
It would be nice to be able to add the option to parse arguments from an environment variable. Is that something this library would be interested in doing or should it be provided by some other library?

**Comment by bkirwi** [comment]
Great question!

Environment var parsing is part of the overall command-line interface, so I think supporting something here would make sense. Presumably, one could add a new case to `Opts`, reuse `Argument` unchanged, and make the necessary changes downstream. 

Early thoughts:
- We should make sure that, if you're not using environment variables, nothing else changes.
- `decline` tries to generate very standard help output: either by working off the POSIX standard, or looking at what most popular UNIXy tools do. AFAIK there's no standardized way to document env vars, so we'd want to survey prior art. (I notice `git` has a section for these; unsure about others.)
- `git` just lists the usable env vars, but has no way to express structure: "this env var must be defined if this option is used", "these two env vars are mutually exclusive", etc. Probably we just live with this, but it means the lib's a bit less useful for env vars than for args.
- It's probably not too hard to integrate env vars into the parser, though it's not obvious to me how you'd want to report errors.

**Comment by bkirwi** [comment]
Thanks for the references!

For the doc: a section with a list of env vars does sound simple, reasonably standard, and probably the right call.

For usage: I imagine we'd want to shoot for something like?

```scala
val command = Command("name", "...") {
  Opts.option[String]("foo", "...") orElse Opts.env("FOO", "...")
}

command.parse(args, env = sys.env) 
```

For parsing: I _think_ we shouldn't have to change the `Accumulator` interface... we should be able to thread the vars through to `Accumulator.fromOpts`, and map `Opts.Env` or whatever to a `Accumulator.Pure` there.

I think we have a sensible path here! I'm unlikely to be able to spend implementation time on this anytime soon myself, but happy to review PRs &c.

**Comment by alexjg** [comment]
Great, I'll try and have a crack at it this week or next.
