### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by rfkm** [bkirwi/decline#33]
I'm running into a performance issue. My app has many options(20 ~ 30) and it takes about 1 minute to parse arguments. It seems the performance is getting worse exponentially according to the number of options. The following is minimal repro:

```scala
object App {
  import cats.syntax.apply._

  def main(args: Array[String]): Unit = {
    val N = 20
    val command = Command("demo", "") {
      (1 to N).map { i =>
        Opts.option[String](s"opt$i", "").withDefault(s"$i")
      }.reduce { (a, b) => (a, b).mapN(_ + _) }.map(println(_))
    }

    while (true) {
      println("Start")
      val s = System.currentTimeMillis()
      command.parse(args) match {
        case Left(help) => println(help)
        case Right(_) =>
      }
      val e = System.currentTimeMillis()
      println(s"Finished took ${e - s}[ms]")
    }
  }
}
```

Output (N=18):
```
Start
123456789101112131415161718
Finished took 1175[ms]
Start
123456789101112131415161718
Finished took 222[ms]
Start
123456789101112131415161718
Finished took 324[ms]
Start
123456789101112131415161718
Finished took 220[ms]
...
```

Output(N=19):
```
Start
12345678910111213141516171819
Finished took 1262[ms]
Start
12345678910111213141516171819
Finished took 553[ms]
Start
12345678910111213141516171819
Finished took 548[ms]
Start
12345678910111213141516171819
Finished took 560[ms]
...
```
Output(N=20):
```
Start
1234567891011121314151617181920
Finished took 2361[ms]
Start
1234567891011121314151617181920
Finished took 1488[ms]
Start
1234567891011121314151617181920
Finished took 1088[ms]
Start
1234567891011121314151617181920
Finished took 849[ms]
...
```

Any thoughts?

**Comment by bkirwi** [comment]
Hey, thanks for the report and minimal repro! That's obviously pretty
unacceptable performance... this is on a 0.4.X release?

**Comment by rfkm** [comment]
Hi, thanks for the reply. Yes, I tested with 0.4.1 (and HEAD).

**Comment by bkirwi** [comment]
Thanks -- I've now reproduced it on HEAD as well. I think I see the issue (too-aggressive normalization in the parser causing an exponential blowup in some cases) though it will take a little longer to get a proper fix up.

**Comment by bkirwi** [comment]
This should be fixed in `0.4.2`, which is percolating out to maven central now. Can you give that a try and see if it behaves well in your codebase also?

**Comment by rfkm** [comment]
I've confirmed it works well. Thanks a lot!

**Comment by bkirwi** [comment]
Thanks again for the report!
