### ISSUE TITLE
Should the values for ChronoUnit be kebab case?

### ISSUE THREAD

**Issue by mdedetrich** [bkirwi/decline#335]
After discussion at https://github.com/bkirwi/decline/pull/331 for adding `ChronoUnit` to pureconfig, a good point was made in that rather then the appropriate values for `ChronoUnit` being snake case they should instead be kebab case (or maybe something else more appropriate). The value that this effects is

```java
HALF_DAYS("HalfDays", Duration.ofSeconds(43200))
```

Currently with my PR at https://github.com/bkirwi/decline/pull/331 we accept either `HALF_DAYS` or `half_days` but maybe another format such as `half-days` is more appropriate.

There is also a discussion whether rather than accepting both `HALF_DAYS` and `half_days` that instead we should only accept a single standard format.

**Comment by bkirwi** [comment]
I don't have strong feelings on this one... _leaning_ towards being as generous as possible in what we accept, since there's no clear winner, but open to the other approaches as well.

**Comment by mdedetrich** [comment]
Will close this for now, if we decide to do something more fancy like whats done with pureconf a separate generic issue should be made about it
