### ISSUE TITLE
Support for effects in CommandApp

### ISSUE THREAD

**Issue by kubukoz** [bkirwi/decline#35]
Hi! I just started using decline and it's looking pretty cool.

Did you consider supporting cats-effect style effects? So that there'd be a variant of `CommandApp` like `CommandApp[Task]`, whose `main` would have to return a `Task[Unit]`.

Additionally, if `Opts` had a `Traverse` instance (didn't think about if it's possible yet, but it should be), we could validate them with effects - let's say I have an `Opts[Path]` and want to make sure that the file exists - which is an IO operation, and I'd rather do it in an effect.

Of course I'm willing to help :)

What do you think?

Thanks!

**Comment by bkirwi** [comment]
> Did you consider supporting cats-effect style effects? So that there'd be a variant of CommandApp like CommandApp[Task], whose main would have to return a Task[Unit].

I have! I think it'd make sense to try and integrate with the new [`IOApp`](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/IOApp.scala) in `cats-effect`, but I haven't looked into it in detail yet.

> Additionally, if Opts had a Traverse instance (didn't think about if it's possible yet, but it should be), we could validate them with effects - let's say I have an Opts[Path] and want to make sure that the file exists - which is an IO operation, and I'd rather do it in an effect.

I'm not totally sure this works... this would lead to code like so:

```scala
val options: Opts[Path] = ???
def validate(path: Path): IO[Path] = ???
val validated: IO[Opts[Path]] = options.traverse(validate)
```

...but it doesn't make much sense to have `IO` on the _outside_; you'd need to run the validation before you even got your hands on the parser!

OTOH, I think there are other ways to get similarly-nice behaviour. I've noticed that `Nested[Opts, IO, ?]` has a pretty nice alternative instance... you get effectively the same behaviour as for regular `Opts`, but with effects that also compose in the obvious way. I haven't had a chance to try this out in real life, though.

**Comment by bkirwi** [comment]
Two points I forgot:
- Really glad you like the libray, and thanks for the suggestion!
- I had figured I'd get around to this problem when I had a couple largish, IO-driven application to play around with: build up a set of utils alongside the code, and then port them here. I haven't got around to this yet... but I'd be delighted to have contributions of that shape!

**Comment by kubukoz** [comment]
Yeah, I get the point about `Traverse` now. Maybe `Opts` could be parameterized by `F[_]`, somehow... guess it'd require a lot of thinking to get it right, so no time now, but I'll see if I have a better idea later :)

As for IOApp, it's cool, but you'd have to convert other effects to IO. Which may not be that painful as you'll only do it once (+ can use e.g. `toIO` on `monix.eval.Task`)...

**Comment by johnynek** [comment]
Yeah. The argument was made that converting to IO once on the outermost level shouldn’t be an issue.

**Comment by DougC** [comment]
I've been thinking about this and, personally, I don't think that `Opts` should be parameterized with an effect type. It seems to me that `Opts` are a way of describing a parser as a pure function from an `List[String]` to a strongly-typed data structure of your choosing. The error handling built into `Opts` deals with syntactic errors and can report help text that describes the syntax, but semantic errors should be left to the application to interpret the data structure.

So, in the example of a file path parameter, `Opts` can deal with it being mandatory or optional, and with the string being a well-formed path name, if you provide an appropriate `Argument` instance. But checking if a file actually exists at that path should be left to the application to do at a "semantic" level inside whatever effect system it uses. This would be reflected in the kind of error message that is produced - either of the first two situations would result in the help text being displayed, but the third situation would result in an application-level error message (e.g. "file not found") and not display the help syntax.

This does leave the issue that `CommandApp` is not parameterized. My first use of `decline` was in an `http4s` application so I wanted to use `IOApp` as my base, which meant I couldn't use `CommandApp`. This meant I had to understand the guts of what `CommandApp` is doing and pull that into my own code, and this situation is not well addressed in the documentation. I would suggest, though, that adding a trait (`CommandParser` perhaps) that could be mixed into the application class to provide a convenience function would deal with that situation.

Just my Monday morning thoughts. I hope they make some sense.

**Comment by bkirwi** [comment]
> It seems to me that Opts are a way of describing a parser as a pure function from an List[String] to a strongly-typed data structure of your choosing. The error handling built into Opts deals with syntactic errors and can report help text that describes the syntax, but semantic errors should be left to the application to interpret the data structure.

Yeah, that's ~basically how I've been thinking about it. You could imagine a design that allowed for effectful validation, but it'd be a substantially more complicated API, and it's not clear much is gained vs. leaving the semantic errors to the application like you say.

> This does leave the issue that CommandApp is not parameterized. My first use of decline was in an http4s application so I wanted to use IOApp as my base, which meant I couldn't use CommandApp. This meant I had to understand the guts of what CommandApp is doing and pull that into my own code, and this situation is not well addressed in the documentation. I would suggest, though, that adding a trait (CommandParser perhaps) that could be mixed into the application class to provide a convenience function would deal with that situation.

I've hesistated here because
- [there's just not that much logic in CommandApp](https://github.com/bkirwi/decline/blob/master/core/shared/src/main/scala/com/monovore/decline/CommandApp.scala#L48-L51)
- it's not as general as you'd want it to be... eg. IOApp has nice support for exit codes that CommandApp does not.

It probably does make sense to have a `decline-effect` submodule that provides some integration with `IOApp`, though, since that's a common desire.

Also, what do you think would help with the docs here? Wondering if putting an example main would set folks on the right path...

```scala
def main(args: Array[String]) = command.parse(args) match {
  case Left(help) =>
    System.err.println(help)
    sys.exit(1)
  case Right(value) =>
    // your code here
}
```

**Comment by DougC** [comment]
> Also, what do you think would help with the docs here? Wondering if putting an example main would set folks on the right path...

Yes, I think that would be very useful, and probably sufficient. Digging out that code from `CommandApp` was the first thing I needed to do and provided a bit of a stumbling block to getting going, so giving new users a clear idea of how to do that would be a big win, I think.
