### ISSUE TITLE
Support optional option arguments

### ISSUE THREAD

**Issue by avdv** [bkirwi/decline#350]
The GNU getopt function supports options that have optional arguments, which means they could be used as flags.

An example is the `--color` option from GNU ls:

* by default -- if the option is not given -- it's value is `auto`
* when using `--color` (as a flag) it has the value `always`
* otherwise, you can specify a value explicitly: `--color=never`

**Comment by bkirwi** [comment]
yep - there's lots of precedent for this, so it would be nice to support. (though as a matter of personal style, i find a separate flag like `--default-color` or whatever is usually more clear.)

the main risk here is around parsing ambiguities... eg. around handling short options where a string `-ab` could be either an argument passed to option `-a` or two flags `-a` and `-b`. but assuming we can come up with something that's unambiguous and consistent with the usual standards ([POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/) etc.) this would be a good inclusion.

i'm unlikely to work on this anytime soon myself, but happy to discuss here if anyone's interested in tackling the implementation.

**Comment by bkirwi** [comment]
Addressed in #415!
