### ISSUE TITLE
How to return a validation error without `help` message

### ISSUE THREAD

**Issue by DieMyst** [bkirwi/decline#411]
In many cases I want to return a validation error without a big help message. But I cannot find how to do this properly. Thanks!

**Comment by bkirwi** [comment]
`Command.parse` returns an instance of `Help`, which is just a case class. If you just want the list of validation errors, you can access the `Help.errors` field.

(Hope that helps!)

**Comment by DieMyst** [comment]
this will definitely help! thank you very much!

**Comment by bkirwi** [comment]
Certainly!
