### ISSUE TITLE
Clarification on `CommandApp` for Scala Native

### ISSUE THREAD

**Issue by aartigao** [bkirwi/decline#414]
I developed a small CLI with Scala Native and `decline` (great lib, by the way 🙂 ), but the docs say:

![image](https://user-images.githubusercontent.com/6449814/166470877-3e8d2e0d-68a4-40b3-b977-fb04b13dbc39.png)

I can confirm that, at least for Scala Native 0.4.4, `CommandApp` works fine.

**Comment by bkirwi** [comment]
Glad to hear it! Making a note to update the docs.

**Comment by bkirwi** [comment]
...and I finally got around to this. Thanks for the report!
