### ISSUE TITLE
Build for Scala Native?

### ISSUE THREAD

**Issue by frgomes** [bkirwi/decline#42]
What would be the complexity for providing decline for Scala Native?
I've seen that it depends on refined, which I do not understand clearly if would be available for Scala Native or not.
It also depends on ScalaTest, which in general can be easily replaced by uTest.
It also depends on ScalaCheck, which I simply would disable in the case of Scala Native.

Can you provide some guidance on how it could be ported?

Thanks

**Comment by bkirwi** [comment]
I think the key dependency to worry about is Cats, and that work is still
in progress:
https://github.com/typelevel/cats/issues/1549

OTOH, I imagine that once they're ready that decline should port over
relatively easily. We already have cross compilation set up for JS, so
supporting Native should be a relatively small additional cost...

**Comment by ziggystar** [comment]
Cats has scala-native support since `2.4.0`. Can we get an update on this issue?
