### ISSUE TITLE
Idea: `Opts#orLeft` and `Opts#orRight`

### ISSUE THREAD

**Issue by morgen-peschke** [bkirwi/decline#434]
Writing an `Opts[Either[A,B]]` in terms of an `Opts[A]` and an `Opts[B]` requires jumping through some hoops:
```
val aOpt: Opts[A] = ???
val bOpt: Opts[B] = ???

val aOrBOpt: Opts[Either[A,B]] = 
 bOpt.map(_.asRight).orElse(aOpt.map(_.asLeft)
```

It would be a nice addition to wrap this in something like this:
```
val aOrBOpt: Opts[Either[A,B]] = aOpt.orRight(bOpt)
val bOrAOpt: Opts[Either[B,A]] = aOpt.orLeft(bOpt)
```

It seems like this would be a common enough case to warrant it's own combinator.

**Comment by bkirwi** [comment]
> It seems like this would be a common enough case to warrant it's own combinator.

You're right, but it seems `Cats` got to it first!

```scala
import cats.implicits._
val aOpt: Opts[A] = ???
val bOpt: Opts[B] = ???

val aOrBOpt: Opts[Either[A,B]] = aOpt sum bOpt
```

`decline` gets quite a lot of general combinators "for free" from Cats like this, which is great, since it keeps `decline`'s surface area small.

**Comment by morgen-peschke** [comment]
Nice!
I swear, there's always another hidden gem in there somewhere :)
