### ISSUE TITLE
Release native artifacts for Scala 3

### ISSUE THREAD

**Issue by mpilquist** [bkirwi/decline#435]
Looks like there are native artifacts for 2.12 and 2.13 but not Scala 3.

**Comment by bkirwi** [comment]
I think that was originally intentional, but it may no longer be necessary... I'll look into it.

**Comment by ghstrider** [comment]
Cats-effect is not released for native.`decline-effect` should also be supported.

**Comment by kubukoz** [comment]
@ghstrider I assume that was a typo, CE is _now_ released for SN :)

Bumping this - looks like https://github.com/bkirwi/decline/pull/440 was merged and just needs to be released.

**Comment by bkirwi** [comment]
Well, since you ask so nicely. :)

`2.3.1` should be out with the changes in #440, including native artifacts. I haven't actually tested pulling down those artifacts yet -- if any of you run into trouble I'd be interested to hear about it!

**Comment by kubukoz** [comment]
thanks @bkirwi, much appreciated!
