### ISSUE TITLE
Subcommands arguments

### ISSUE THREAD

**Issue by plmuninn** [bkirwi/decline#50]
Is there a way or plan to display arguments for subcommands?

I think it would be handy to have them in detail in Subcommands section and in usage part with shorter version.

**Comment by johnynek** [comment]
I can imagine ways to send options to build the help screen. The default could use some heuristic to try fit on one page, if you have a simple help show the whole help.

But you could also have a way users could customize the help message.

**Comment by OneWebPro** [comment]
@bkirwi I get you, but I also think library like this should give you some ways of handling requirements like that. I'm now working on CLI where having full options would be perfect. Right now I was able to display Help manually but its really "ugly" way of doing it.
I also tried to fork decline and implement it, I did subcommands argument descriptions without problem but I failed on displaying arguments in usage part. 

@johnynek I don't think it should be configurable per se - maybe just Help should have different forms / subtypes, type class for displaying it or smth.

**Comment by bkirwi** [comment]
Yeah, it's an interesting balance.

One way to go about it would be to capture more structure in the `Help` case class, so that you could pull information from it in more interesting ways. But I'd still prefer keeping the interface small if we can swing it.

One good avenue into the question -- are there popular CLI tools with usage text that uses the style you're suggesting? eg. alexjg did a great job collecting [examples and prior art](https://github.com/bkirwi/decline/issues/32) for a previous change.

**Comment by ivan-klass** [comment]
Just thinking in loud: what if having something like
```scala
trait HelpPolicy {
   def displayIfShallower(depth: Int): Boolean
}
object HelpPolicy {
  def limitDepth(limit: Int) : HelpPolicy = _ <= limit
  implicit val defaultHelpPolicy: HelpPolicy = limitDepth(1)
}
```
so we need an instance for that when parsing or when generating help options

**Comment by bkirwi** [comment]
I think in practise that ends up equivalent to...

```scala
val help: Help = ???
help.display(ifShallower = 1)
```

I've been trying not to introduce too many typeclasses etc. if possible... nice to keep the library small!

Re: the depth idea... I'm definitely supportive of keeping enough structure in the Help that you could do such things, but I'm not sure I'd want to have that rendering method built in. (The built-in stuff tries to follow bog-standard UNIX idioms, and I've never seen another UNIX tool render stuff that way. Would consider it if folks find examples though!)

**Comment by ivan-klass** [comment]
Totally agree that structured help is a most flexible choice!

**Comment by bkirwi** [comment]
Closing in favour of #138!
