### ISSUE TITLE
Broken link on website documentation

### ISSUE THREAD

**Issue by lm-dt** [bkirwi/decline#504]
In the 'arguments.html' page, right at the top, there's a broken link to the guide, in the line with:
```
In the [guide](https://ben.kirw.in/usage.html), we specified the type of an option’s argument like so:
```
I assume you meant to point to `https://ben.kirw.in/decline/usage.html`

Thanks for making this, by the way!

**Comment by lm-dt** [comment]
Just noticed another one in the readme - the scala code of conduct seems to have moved (I see the same broken link on other typelevel projects) to `https://typelevel.org/code-of-conduct`

**Comment by bkirwi** [comment]
Thanks for the heads up! I'll get those sorted out.
