### ISSUE TITLE
set up maven central publishing

### ISSUE THREAD

**Issue by johnynek** [bkirwi/decline#6]
I'd like to use decline from some bazel projects, and I don't want to have to figure out bintray support.

Any chance we can just do maven central?

**Comment by bkirwi** [comment]
I _think_ I got the issues with this one sorted out -- will confirm next time I do a release!

**Comment by optician** [comment]
Bintray can synchronize with central.

**Comment by bkirwi** [comment]
Yep -- central is just slightly more strict about what you can publish (eg. the pom needs a project url) so I can't just sync an existing release. I'm hoping to cut a new release in ~one week, so I should be able to close this then.

**Comment by bkirwi** [comment]
(Had a little trouble getting perms set up, but this is all sorted now!)
