### ISSUE TITLE
Document behaviour for the top-level command name

### ISSUE THREAD

**Issue by BenHutchisonSeek** [bkirwi/decline#63]
When subcommands are composed under a top command, the resultant parser wont accept the top command. See ammonite REPL session for example:
```
Welcome to the Ammonite Repl 1.4.2
(Scala 2.12.7 Java 11.0.1)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import $ivy.`com.monovore:decline_2.12:0.6.2`
import $ivy.$

@ import cats.implicits._
import cats.implicits._

@ import com.monovore.decline._
import com.monovore.decline._

@
Command("top", "top")(Opts.subcommand(Command("Sub1", "sub1")(Opts.unit)).orElse(Opts.subcommand(Command("Sub2", "sub2")(Opts.unit)))
)
res3: Command[Unit] = com.monovore.decline.Command@5ab5924c

@ res3.showHelp
res4: String = """Usage:
    top Sub1
    top Sub2

top

Options and flags:
    --help
        Display this help text.
...

@ res3.parse(List("top", "Sub1"))
res5: Either[Help, Unit] = Left(
  Help(
    List("Unexpected argument: top"),
    NonEmptyList("top", List()),
    List("Sub1", "Sub2"),
    List(
      "top",
      """Options and flags:
    --help
...
```

I'd expect that input `List("top", "Sub1")` should be parsed to `Right(Unit)`. That's shown as valid input in the generated help text.

**Comment by bkirwi** [comment]
> When subcommands are composed under a top command, the resultant parser wont accept the top command.

The parser doesn't accept the top-level command in any case; for example:

```
scala> val command = Command("top", "top") { Opts.unit }
command: com.monovore.decline.Command[Unit] = com.monovore.decline.Command@649cf9f3

scala> command.parse(List("top"))
res1: Either[com.monovore.decline.Help,Unit] =
Left(Unexpected argument: top

Usage: top

top

Options and flags:
    --help
        Display this help text.)

scala> command.parse(List())
res2: Either[com.monovore.decline.Help,Unit] = Right(())
```

The idea is that, for the top-level command, the command name _is the program name_. Thinking from a perspective of a user, when they see the help text you pasted, they'd expect to type `top Sub1` in their shell and get a valid parse... which means that only `Sub1` is an actual argument to the program. 

If you do want to use nested _subcommands_, those work as you'd expect:

```
scala> Command("top", "top") { Opts.subcommand("a", "a") { Opts.subcommand("b", "b") { Opts.unit } } }
res3: com.monovore.decline.Command[Unit] = com.monovore.decline.Command@391d65fd

scala> res3.parse(List("a", "b"))
res4: Either[com.monovore.decline.Help,Unit] = Right(())
```

The docs should call out that the top-level command should be named the same thing as your program, etc... I'll follow up on that!

**Comment by BenHutchisonSeek** [comment]
OK, makes sense. I think the issue then is simply to make that clearer in the docs.

**Comment by bkirwi** [comment]
Cool, sounds good -- I'll keep this issue open for that work then.
