### ISSUE TITLE
Setup gitter room

### ISSUE THREAD

**Issue by Krever** [bkirwi/decline#68]
What do you think about having faster communication channel? 
If agreed to set it up then lets remember about badge in readme :)

**Comment by mslinn** [comment]
Accessing the decline private gitter room requires me to allow gitter to read and write all my private repos!!!! No can do.

**Comment by Krever** [comment]
I'm not sure about private rooms (didnt even know those exist), but I know a lot of projects (e.g. majority of typelevel ones) has standard rooms, so maybe its not that bad.

Anyway, don't want to force anything here :)

**Comment by mslinn** [comment]
@Krever Sounds like you don't realize that the Chat tab at the bottom of http://ben.kirw.in/decline/usage.html asks the user to join a private gitter room.

**Comment by Krever** [comment]
Yes, I didn't realize indeed! 

Sadly, the button gives me `404` error when I try to access the room. Most probably because its private :) 

Is there any reason you don't want a public one?

**Comment by mslinn** [comment]
@Krever You misunderstand. A public room is what is needed, thanks.

**Comment by bkirwi** [comment]
Hey, thanks for flagging this! The gitter link was added recently by the `sbt-microsites` plugin we use, which I updated a few days ago, and I missed it in the release notes. I've now disabled it; sorry for the confusion!

I'm hesitant to actually set up a public gitter:
- I personally don't hang out in chat during the day, so my response time is likely to be the same as for issues.
- Questions in issues are more searchable, which makes them more useful for the next person with a similar question.

I think that would be outweighed if there was a critical mass of folks who _would_ hang out in gitter and want to answer questions / etc. (if you are such a person, announce yourself!) but absent that I'll leave it disabled.

**Comment by Krever** [comment]
I'm definitely the one who hang out on gitter. And it's pretty common to users help each other without maintainers attendence. 
Also I find people are much more eager to ask questions on gitter because a lot of maintainers don't like them asked via issues (keeping it for for bug reports only).

So, I would give it a short, but that's why I opened the issue ;) The call is still on you and we can wait for more people to show interest.

**Comment by TonioGela** [comment]
@Krever I'm showing interest more than an year later :P

**Comment by bkirwi** [comment]
FWIW I've now opened up the GitHub discussions tab: https://github.com/bkirwi/decline/discussions

Probably not quite what folks here are looking for, but maybe a better for open-ended questions etc.!

**Comment by bkirwi** [comment]
And we now have a room in the Typelevel discord: https://discord.com/channels/632277896739946517/895394320100761731

I'm relatively comfortable supporting this - there are quite a few folks familiar with `decline` who already hang out in that discord. But I'd encourage folks to use the discussions link above when they have a well-formed question, to keep things more structured and searchable when that makes sense.

I'll look into getting a badge / link on the microsite, but I'm closing this one for now. Thanks to those who expressed interest, and you're certainly extremely welcome to come hang out even when you don't have any particular burning questions...
