### ISSUE TITLE
ScalaJs support

### ISSUE THREAD

**Issue by 13h3r** [bkirwi/decline#8]
We need to remove (or extract) `Path` `Argument` to make it possible to use it from scalajs. WDYT?

**Comment by bkirwi** [comment]
I'd be enthusiastic about supporting scalajs here, but I'd much prefer extracting to removing -- `Path` is a _very_ common arg type on the JVM, so having `Argument[Path]` in implicit scope is a really nice affordance. Adding a platform-specific `PlatformArguments` trait, moving the `implicit val pathArgument` there, and having `object Argument extends PlatformArguments` ought to do the trick?

(The _other_ nice thing for scalajs would be to have a version of `CommandApp` that worked with node / etc. -- but that's probably less important.)

If you have time to work this up, I'd be delighted to get a PR for this!

**Comment by bkirwi** [comment]
(Have some time this week -- I'll take a stab at it.)

**Comment by 13h3r** [comment]
I did a quick try. Looks like we just need to put instance of `Argument[Path]` into another object (even in the same file) and it should work for scalajs.

**Comment by bkirwi** [comment]
Neat, thanks!

I sketched this up in #9 -- ended up breaking out the instance into a platform-specific superclass, so we can keep the same resolution behaviour on the JVM. Interested in feedback if you get a chance to try it out... I'll aim to cut a proper release sometime later this week.

**Comment by bkirwi** [comment]
Released in 0.3.0! Documented here: http://ben.kirw.in/decline/scalajs.html
